using LeetCodeDaily.Core;

Case
    .CreateCase(
        ("PAYPALISHIRING", 3),
        "PAHNAPLSIIGYIR")
    .CreateCase(
        ("ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ", 5),
        "AIQYGOWEMUCKSAIQYGOWEMUCKSAIQYGOWEMUCKSAIQYGOWEMUBHJPRXZFHNPVXDFLNTVBDJLRTZBHJPRXZFHNPVXDFLNTVBDJLRTZBHJPRXZFHNPVXDFLNTVBDJLRTZBHJPRXZFHNPVXDFLNTVCGKOSWAEIMQUYCGKOSWAEIMQUYCGKOSWAEIMQUYCGKOSWAEIMQUYCGKOSWAEIMQUYCGKOSWAEIMQUYCGKOSWAEIMQUYCGKOSWDFLNTVBDJLRTZBHJPRXZFHNPVXDFLNTVBDJLRTZBHJPRXZFHNPVXDFLNTVBDJLRTZBHJPRXZFHNPVXDFLNTVBDJLRTZBHJPRXZEMUCKSAIQYGOWEMUCKSAIQYGOWEMUCKSAIQYGOWEMUCKSAIQY")
    .CreateCase(
        ("PAYPALISHIRING", 4),
        "PINALSIGYAHRPI")
    .CreateCase(
        ("A", 1),
        "A")
    .CreateCase(
        ("ABC", 2),
        "ACB")
    .CreateCase(
        ("ABCD", 2),
        "ACBD")
    .Detect()
    .Run()
    .Detect(1)
    .Run();