using LeetCodeDaily.Core;
using System.Numerics;

namespace _1545.Find_Kth_Bit_in_Nth_Binary_String;

public class Solution
{
    [ResultGenerator]
    public char FindKthBit(int n, int k)
    {
        // The n-th binary string is generated by taking the (n-1)-th binary string,
        // concatenating '1', and then concatenating the reverse of the (n-1)-th binary string with all bits inverted.

        /*
         * S1 = "0"                                                                                                  // len = 1
         * S2 = S1 + "1" + Reverse(Invert(S1)) = "0" + "1" + Reverse("1") = "0" + "1" + "1" = "011"                  // len = 3
         * S3 = S2 + "1" + Reverse(Invert(S2)) = "011" + "1" + Reverse("100") = "011" + "1" + "001" = "0111001"      // len = 7
         * S4 = "011100110110001"                                                                                    // len = 15
         * S5 = "011100110110001" + "1" + "011100100110001"                                                          // len = 31
         */

        // The given constraint "It is guaranteed that k is valid for the given n." makes "n" redundant,
        // since the binary string S(n+1) uses the same base / start as S(n).

        // One observation we can make is that if k is a power of 2, then the k-th bit will always be '1' (except for k = 1, which is '0').
        // Those indexes do not depend on previous iterations.
        // S(2) = "0" + ["1"] + "1"                                      // fixed '1' at index 2 (starting from 1)
        // S(3) = "0[1]1" + ["1"] + "100"                                // fixed '1' at indexes 2, 4 (starting from 1)
        // S(4) = "0[1]1[1]001" + ["1"] + "0110001"                      // fixed '1' at indexes 2, 4, 8 (starting from 1)
        // S(5) = "0[1]1[1]001[1]0110001" + ["1"] + "011100100110001"    // fixed '1' at indexes 2, 4, 8, 16 (starting from 1)

        // Another observation is that S(n)[p] (binary string of n at index p)
        // can also be expressed as Invert(S(n)[q]) (the inverted bit at index q)
        // where q is the index of the bit that is mirrored to p in the reverse part of the string.
        // To find q, we can find the largest power of 2 that is smaller than k (let's call it "anchor"),
        // and then calculate q as "anchor - (k - anchor)".


        // Example: n = 5, k = 26
        //
        // S(5) = "011100110110001" +                           "1"                          + "011100100110001"
        //
        //        [1--2--3--4--5--6--7--8--9-10-11-12-13-14-15--16--17-18-19-20-21-22-23-24-25--26--27-28-29-30-31]
        // S(5) = "0  1  1  1  0  0  1  1  0  1  1  0  0  0  1  [1]  0  1  1  1  0  0  1  0  0  [1]  1  0  0  0  1  ..."
        //                                                                                       ^ we want this bit (k = 26)  
        //                                                       ^ this is the "anchor" (largest power of 2 smaller than k, which is 16 in this case)
        //                                                      [  distance between k and anchor  ] = 10
        //                        ^ we select our new k (q) as the bit that is mirrored to the original k in the reverse part of the string, which is "anchor - distance" = 6
        //                        [       16 - distance = 6       ]
        //
        // So, S(5) at index 26 is the invertation of S(5) at index 6:
        //
        // S(5)[26] = Invert(S(5)[6])
        // 
        // Now, we repeat the process until we find a k that is either 1 (which is always '0') or a power of 2 (which is always '1'),
        // and we count the number of times we had to invert the bit along the way.
        //
        // For k = 6, the next smaller power of 2 is 4 (our next "anchor"), so the next mirrored index is at:
        // anchor - (k - anchor) = 4 - (6 - 4) = 2
        // 
        // So:
        // S(5)[6] = Invert(S(5)[2])
        //
        // Therefore:
        // S(5)[26] = Invert(S(5)[6]) = Invert(Invert(S(5)[2])) = S(5)[2] = '1'
        // 
        // Since 2 is a power of 2 (which are always '1'), we can stop here and return Invert(Invert('1')) as the result.

        if (k <= 1)
            return '0';

        int inverts = 0;
        int res = 0;

        while (true)
        {
            // next smaller power of 2 (anchor) can be found by counting the number of leading zeros in k, and then shifting 1 to the left by 31 minus that count.
            var anchor = 1 << (31 - BitOperations.LeadingZeroCount((uint)k));

            // we count the number of times we had to invert the bit along the way
            // special case: if k is already an anchor, we don't need to invert it
            if (k != anchor)
            {
                inverts++;
            }

            // mirroring k along the anchor
            k = anchor - (k - anchor);

            // PopCount returns "1" for powers of 2 (which is what we want to stop at)
            if (int.PopCount(k) <= 1)
            {
                // if our k is a power of 2, we set res (our base value) to 1, otherwise it will stay 0 (which is the case for k = 1).
                if (k > 1)
                {
                    res = 1;
                }

                break;
            }
        }

        // If the number of inverts is even, we return the bit as it is (res), otherwise we return the inverted bit (1 - res).
        return (char)(((res + inverts) % 2) + '0');
    }
}