using LeetCodeDaily.Core;
using LeetCodeDaily.Extensions;

"""
ayvcnlvxbuzlnitercfchxbwdtvrjwbiwncthyvzgrtyvjwvlygyugzyzedwbemgvbheczijoylfsyqoidijwvofdnjaslnsadkzvglwwioipilqcrxfzhxuikmrrgylzbamorwbgexgbxisdjejogkendmxfytnjtrzhltikphpcqzfsqqcxdoesccqxojjqrgbjeioukogcicoigwbdatzhblzsierdvdjewztnokukmkghvhpwtbzenlelkjcfvadfizrxsntsgddbsnawbdwcubamddaoonqtgigxwnnvfyzgzucbsjstqvsbocjucrxbkeasmllyxlwbfqtnnrntqhlzsfxcenjczljawkgdvcbdxpzcqtnbocsspdbffunsqbygevefljkvtowbnomatymkghdfswlqpmcmsxwsnhyiirpmnitzqwzyhevktkkndsgbcnrcafjavpflyzaawienayqlpzszwypbkpzvnhtggjmtwgxpbuxcfkwaxsxwhrpkvoeiyzviksuwjpoddcjskb
wyopxwamgayztpxnoulqbhnunymnxcxthsyvfujeiobginckvzevdihhtdnvilwdydiqxykdlwxjqhsushzyoglxrbnvttftzryzivirmussmkrqwtvcajpnkdywfvwnhzcthamsvepbzeartkbldmoumitruoqjnplbcubxnmyuxyptljllmzqzwsphknvnbfxacqvjkfznnpdrheevmfbkqxomccmjipcacxryxsykxnuyhvkbbjmoylayxrkbyfrbnxebandtcpqywheslcoxgcvvtzvwoblzpwdmoxwplehyddekjasvaedzlyqdgmqlzvxuzwotfrficdqctyzzmftavhlxhsokdlmxyzyrtvjeptdfgeczpndvpyzmmcatfifedvgntqxmjvwwutjhcsrxfafvzsmqlqdividcmozfdaxotmxalconnkicupzzwmvnxpvynkmcrxkjdqyjrjmxgezyzzkjjjxsczkrbeesudqcyfzfqjatqatztpeagrxpjzmrvgglopgcqrotuccdxaq
false

a
a
true

a
b
false

ab
ba
false

abcd
cdab
true

abcd
dacb
false

ababababababababababababababababababababababababababababababababababababababababababababababababab
bababababababababababababababababababababababababababababababababababababababababababababababababa
false

abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
cbadfegihjklmonprqtsuvwxzyabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
false

zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyz
false

yviqgzqwetjqwnmmbupitdsjdvophjhkiivtbsgehlxzestjjrqwahxcaafafgdxjiocwgnqbmoxbcbpiwz
yjowhiiitgdesjzjwvqqnuonirjggtbpjmpwmzapjsbcqahxfidqoxotbavmfzbcblxvesxwgcahhqwkedi
false
"""
.ParseCases<(string, string), bool>()
.DetectAndRun();