using LeetCodeDaily.Core;
using LeetCodeDaily.Extensions;

string cases =
"""
Y
1

N
0

NY
0

YN
1

NYN
0

YNY
1

YNNYYNNYYNYNNNNNYNYNYNNYNNYYYNNNNYYYNYNYNYYYNYNYYYYYYNNYNNNYYNYYYNNYYYYYNNYYNYNYNYNNNYYNNYYYYNYYYYNNNYNYNYNYYNNYYNNNYNNYYYNNYNNYYYNNNNYYYYNYNYNYYNNNNYNNNYNYNYYYNNNNNNNYNYYYYYNYYNNYNYNYNNNYYNYNNNYYNYNY
98

NNNNNYYYYYNYYYNNNYYYNYNNYNYYYNYNNNNNNNNYNNNYYNNNNNYNYNNNYYNNNYYNYYNYYNYYNNNYNNNNYNNYYNNNYNNYNNYNYYYYYNNYNNNYNYYYNNNYYYYYNYYYNNNNYYNYNYYNNYYYYNYNNYYNNYNYYNNNNYNYNNNNYYYNNNYYYYYNNYNYNNYNNYNYNYNYNYYNYYY
29
""";

cases
    .ParseCases<string, int>()
    .DetectAndRun()
    .DetectAndRun(1);