using LeetCodeDaily.Core;
using LeetCodeDaily.Extensions;

string cases =
"""
SSPPSPS
3

PPSPSP
1

S
0

P
0

S
0

PPPSPPPSPSSPPSPSSPSSPPPPSSPSSPPSPPPSSSPSSSPSSSSPSSSSSPSSPSPPSSPSSPPSSSPSPPPSSSSSPSSPPPSSPPSSPSSSPPSP
0

PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
0

PSPSPPPSSSSPSSPSSPSPPSSSPPSPSPPPSSSPSPPSSSPSSSPPSPPPSPSPPPSPSPPSSPPSSPSPSSPPPPPSPSPSSSPSSSSPPPSPSPPS
663552
""";

cases
    .ParseCases<string, int>()
    .DetectAndRun();